### PR TITLE
Added optionals UserProfile input for createUser

### PR DESCRIPTION
**Pull request by janikvonrotz**
Also updated the Readme. Is this ok? I want to keep it as simple as
possible.

#15

### CODE REVIEW

**Comment by janikvonrotz** [comment]
Is the naming alright?

**Comment by janikvonrotz** [comment]
@nicolaslopezj didn't hear anything from you yet. Is there anything you would like to have changed?

**Comment by nicolaslopezj** [comment]
Sorry for the delay...

Can you rename ```UserProfileInput``` to ```CreateUserProfileInput``` to make it more specific and avoid conflicts.

What if the user not provides options for the user profile?

You could add a option to ```SchemaMutations``` to make the ```CreateUserProfileInput``` optional or not, so for example developers can force the user to pass the name

**Comment by janikvonrotz** [comment]
I renamed it and updated my pr.

If the user provides the `CreateUserProfileInput` type without `!` required properties, they are optional on the client call.
If he provides the `CreateUserProfileInput` type with `!` required properties, they are required on the client call.

I haven found a solution for these cases yet:

- The `CreateUserProfileInput` is not provided in schema.
- The `CreateUserProfileInput` provided with an empty string.

This is because of these two constraints:

- The `createUser` mutation expects an input type named `CreateUserProfileInput`.
- The `CreateUserProfileInput` type must have keys.

Do you haven idea how to solve this?

**Comment by nicolaslopezj** [comment]
To solve this we can set a default ```CreateUserProfileInput```:

```graphql
# Default profile input
input CreateUserProfileInput {
  name: String
}
```

**Comment by janikvonrotz** [comment]
Fixed it. Do you like this solution?

**Comment by nicolaslopezj** [comment]
Looks great. I'm going to test later today

**Comment by nicolaslopezj** [comment]
Published versions:

- meteor-apollo-accounts@1.3.0
- nicolaslopezj:apollo-accounts@2.0.0

**Pull request merged**
